const $=s=>document.querySelector(s);
const DEFAULT={'index.html':'<main><h1>Olá 👋</h1><p>Seu projeto aparece aqui.</p></main>','style.css':'body{font-family:system-ui;padding:30px}','script.js':'console.log("Projeto iniciado")'};
let files=JSON.parse(localStorage.getItem('zero.files')||'null')||DEFAULT,active=Object.keys(files)[0],busy=false,conversation=[];
const API='/chat';
function save(){localStorage.setItem('zero.files',JSON.stringify(files))}
function tabs(){let n=$('#tabs');n.textContent='';Object.keys(files).forEach(f=>{let b=document.createElement('button');b.textContent=f;b.className=f===active?'active':'';b.onclick=()=>openFile(f);n.append(b)})}
function openFile(f){if(files[active]!=null)files[active]=$('#editor').value;active=f;$('#editor').value=files[f]||'';save();tabs();lines()}
function lines(){let n=$('#editor').value.split('\n').length;$('#lines').textContent=Array.from({length:n},(_,i)=>i+1).join('\n')}
$('#editor').oninput=()=>{files[active]=$('#editor').value;save();lines()};
function message(type,text=''){let d=document.createElement('div');d.className=type;d.textContent=text;$('#messages').append(d);$('#messages').scrollTop=1e9;return d}
function status(t){$('#status').textContent=t}
function projectContext(){return Object.entries(files).map(([n,c])=>`ARQUIVO ${n}:\n${c}`).join('\n\n').slice(0,10000)}
function applyFiles(text){let re=/<<<FILE:([^>]+)>>>([\s\S]*?)<<<END_FILE>>>/g,m,changed=[];while((m=re.exec(text))){let name=m[1].trim().replace(/^\/+/,''),content=m[2].replace(/^\n/,'').replace(/\n$/,'');if(!/^[\w.\-\/]+$/.test(name))continue;files[name]=content;changed.push(name)}if(changed.length){save();active=changed.includes(active)?active:changed[0];$('#editor').value=files[active]||'';tabs();lines();run()}return changed}
function visibleReply(text){return text.replace(/<<<FILE:[^>]+>>>[\s\S]*?(?:<<<END_FILE>>>|$)/g,'').trim()}
function extractText(data,raw){const candidates=[data?.response,data?.text,data?.output_text,data?.message,data?.result?.response,data?.result?.text,data?.result?.output_text,data?.choices?.[0]?.message?.content,data?.result?.choices?.[0]?.message?.content];for(const x of candidates)if(typeof x==='string'&&x.trim())return x;if(typeof data?.result==='string'&&data.result.trim())return data.result;if(data&&typeof data==='object'){const s=JSON.stringify(data);if(s&&s!=='{}')return s}return raw||''}
async function send(){let p=$('#prompt').value.trim();if(!p||busy)return;message('user',p);$('#prompt').value='';busy=true;$('#send').disabled=true;let a=message('ai','Pensando…');try{status('🧠 CodeZero pensando…');let r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:p,project:projectContext(),history:conversation.slice(-4)})});let raw=await r.text();let data=null;try{data=JSON.parse(raw)}catch{}if(!r.ok){let detail=data?.details||data?.error||raw||`HTTP ${r.status}`;throw new Error(`CodeZero ${r.status}: ${String(detail).slice(0,500)}`)}let full=extractText(data,raw);if(!full.trim())throw new Error('O CodeZero respondeu vazio.');let changed=applyFiles(full);conversation.push({role:'user',content:p},{role:'assistant',content:full});conversation=conversation.slice(-6);a.textContent=(visibleReply(full)||'Código atualizado.')+(changed.length?'\n\n✓ '+changed.join(', '):'');status('✅ CodeZero respondeu')}catch(e){console.error(e);a.textContent='Erro da IA: '+e.message;status('⚠️ '+e.message.slice(0,80))}finally{busy=false;$('#send').disabled=false}}
function run(){files[active]=$('#editor').value;save();$('#console').textContent='';let bridge=`<script>['log','error','warn'].forEach(k=>{let o=console[k];console[k]=(...a)=>{parent.postMessage({zero:1,k,a},'*');o(...a)}});onerror=e=>parent.postMessage({zero:1,k:'error',a:[e.message]},'*')<\/script>`;let js=(files['script.js']||'').replaceAll('</script','<\\/script');$('#preview').srcdoc=`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none';connect-src 'none';img-src data: blob:;style-src 'unsafe-inline';script-src 'unsafe-inline'"><style>${files['style.css']||''}</style>${bridge}${files['index.html']||''}<script>${js}<\/script>`}
window.onmessage=e=>{if(e.data?.zero)$('#console').textContent+=`${e.data.k}: ${e.data.a.join(' ')}\n`};
$('#send').onclick=send;$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('#run').onclick=run;$('#theme').onclick=()=>document.body.style.filter=document.body.style.filter?'':'invert(.9) hue-rotate(180deg)';$('#editor').value=files[active];tabs();lines();run();status('☁️ CodeZero • Railway');