import * as webllm from 'https://esm.run/@mlc-ai/web-llm';
const $=s=>document.querySelector(s);
const DEFAULT={'index.html':'<main><h1>Olá 👋</h1><p>Seu projeto aparece aqui.</p></main>','style.css':'body{font-family:system-ui;padding:30px}','script.js':'console.log("Projeto iniciado")'};
let files=JSON.parse(localStorage.getItem('zero.files')||'null')||DEFAULT,active=Object.keys(files)[0],engine=null,loading=false,conversation=[];
const MODEL_CANDIDATES=['Qwen2.5-Coder-1.5B-Instruct-q4f16_1-MLC','Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC','Qwen2-1.5B-Instruct-q4f16_1-MLC','Qwen2-0.5B-Instruct-q4f16_1-MLC'];
function save(){localStorage.setItem('zero.files',JSON.stringify(files))}function tabs(){let n=$('#tabs');n.textContent='';Object.keys(files).forEach(f=>{let b=document.createElement('button');b.textContent=f;b.className=f===active?'active':'';b.onclick=()=>open(f);n.append(b)})}function open(f){if(files[active]!=null)files[active]=$('#editor').value;active=f;$('#editor').value=files[f]||'';save();tabs();lines()}function lines(){let n=$('#editor').value.split('\n').length;$('#lines').textContent=Array.from({length:n},(_,i)=>i+1).join('\n')}$('#editor').oninput=()=>{files[active]=$('#editor').value;save();lines()};
function message(type,text=''){let d=document.createElement('div');d.className=type;d.textContent=text;$('#messages').append(d);$('#messages').scrollTop=1e9;return d}function status(t){$('#status').textContent=t}
async function loadAI(){if(engine||loading)return;loading=true;$('#loadAI').disabled=true;if(!('gpu' in navigator)){status('❌ WebGPU indisponível neste navegador');message('ai','Este navegador não expõe WebGPU. Atualize o Chrome/Android e tente novamente.');loading=false;return}let available=new Set(webllm.prebuiltAppConfig.model_list.map(x=>x.model_id));let model=MODEL_CANDIDATES.find(x=>available.has(x));if(!model){model=webllm.prebuiltAppConfig.model_list.find(x=>/qwen.*(?:coder|0\.5b|1\.5b)/i.test(x.model_id))?.model_id}if(!model){status('❌ modelo leve compatível não encontrado');loading=false;return}try{status('Preparando '+model+'…');engine=await webllm.CreateMLCEngine(model,{initProgressCallback:r=>status('🧠 '+r.text),appConfig:{...webllm.prebuiltAppConfig,cacheBackend:'indexeddb'}},{context_window_size:4096});status('✅ IA local pronta • '+model);$('#loadAI').textContent='✅ IA pronta'}catch(e){console.error(e);status('❌ Falha ao carregar IA');message('ai','Falha ao carregar o modelo local: '+e.message);engine=null;$('#loadAI').disabled=false}finally{loading=false}}
const SYSTEM=`Você é CodeZero, um engenheiro de software que trabalha dentro de uma IDE web. Responda sempre em português simples. Você recebe os arquivos atuais do projeto. Quando o usuário apenas conversar ou fizer pergunta, responda normalmente. Quando ele pedir criação ou alteração de código, devolva primeiro uma explicação curta e depois, para cada arquivo que deve ser criado/substituído, um bloco EXATAMENTE neste formato:\n<<<FILE:nome.ext>>>\nconteúdo completo\n<<<END_FILE>>>\nArquivos web suportados inicialmente: index.html, style.css, script.js. Nunca use markdown dentro dos marcadores. Gere código completo e funcional. O preview não possui rede; não dependa de APIs externas. Preserve o que já funciona quando o pedido for uma alteração.`;
function projectContext(){return Object.entries(files).map(([n,c])=>`ARQUIVO ${n}:\n${c}`).join('\n\n')}
function applyFiles(text){let re=/<<<FILE:([^>]+)>>>([\s\S]*?)<<<END_FILE>>>/g,m,changed=[];while((m=re.exec(text))){let name=m[1].trim().replace(/^\/+/,''),content=m[2].replace(/^\n/,'').replace(/\n$/,'');if(!/^[\w.\-\/]+$/.test(name))continue;files[name]=content;changed.push(name)}if(changed.length){save();if(!files[active])active=changed[0];$('#editor').value=files[active]||'';tabs();lines();run()}return changed}
function visibleReply(text){return text.replace(/<<<FILE:[^>]+>>>[\s\S]*?<<<END_FILE>>>/g,'').trim()}
async function send(){let p=$('#prompt').value.trim();if(!p)return;message('user',p);$('#prompt').value='';if(!engine){let a=message('ai','');a.textContent='A IA real ainda não está carregada. Toque em “🧠 Carregar IA”.';return}let a=message('ai',''),full='';let userContent=`Pedido do usuário: ${p}\n\nProjeto atual:\n${projectContext()}`;let msgs=[{role:'system',content:SYSTEM},...conversation.slice(-6),{role:'user',content:userContent}];try{status('✍️ IA pensando localmente…');let chunks=await engine.chat.completions.create({messages:msgs,temperature:.25,max_tokens:1800,stream:true});for await(const chunk of chunks){let d=chunk.choices?.[0]?.delta?.content||'';full+=d;let v=visibleReply(full);a.textContent=v||'Escrevendo código…';$('#messages').scrollTop=1e9}let changed=applyFiles(full);conversation.push({role:'user',content:p},{role:'assistant',content:full});if(changed.length)a.textContent=(visibleReply(full)||'Código atualizado.')+'\n\n✓ Arquivos atualizados: '+changed.join(', ');status('✅ IA local pronta')}catch(e){console.error(e);a.textContent='Erro durante a geração local: '+e.message;status('⚠️ erro na geração')}}
function run(){files[active]=$('#editor').value;save();$('#console').textContent='';let bridge=`<script>['log','error','warn'].forEach(k=>{let o=console[k];console[k]=(...a)=>{parent.postMessage({zero:1,k,a},'*');o(...a)}});onerror=e=>parent.postMessage({zero:1,k:'error',a:[e.message]},'*')<\/script>`;let js=(files['script.js']||'').replaceAll('</script','<\\/script');$('#preview').srcdoc=`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none';connect-src 'none';img-src data: blob:;style-src 'unsafe-inline';script-src 'unsafe-inline'"><style>${files['style.css']||''}</style>${bridge}${files['index.html']||''}<script>${js}<\/script>`}window.onmessage=e=>{if(e.data?.zero)$('#console').textContent+=`${e.data.k}: ${e.data.a.join(' ')}\n`};
$('#loadAI').onclick=loadAI;$('#send').onclick=send;$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('#run').onclick=run;$('#theme').onclick=()=>document.body.style.filter=document.body.style.filter?'':'invert(.9) hue-rotate(180deg)';$('#editor').value=files[active];tabs();lines();run();